version: "3.9"
services:
  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
